### PR TITLE
Responsive Layout

### PR DESCRIPTION
**Pull request by rootDEV2990**
Please help us review our responsive attempt at cloning TNW magazine. Please leave us a comment and thank you for your time.

### CODE REVIEW

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes ♻️ 🚥 

Hi **Team**, you have done a great job 👍 Your project is responsive 👐 , However, we need to make a few changes in order to approve the project. Find comments below:
* ```The TNW logo``` is not appearing in the large screen. Kindly add it. Currently, this is how it looks. Let us compare the width and margin
av1
```Original version```
av2
* The spacing in the nav is not consistent. Check image below
av7
* Let us fix the icons in the footer and some padding. Currently, it looks like this 
av4
```Original version```
av5
* ```Small screen```, the footer icon breaks. Kindly check the image below to fix it
av6
* Currently, we are missing the main navigation link
av8
[OPTIONAL]
Kindly reduce the font size of the text in the images
av9

Kindly make these changes and submit another code review 🙂 
_Happy coding_ 👨‍💻 
Find me on slack @ **Daniel Larbi Addo**

**Review by euqueme — CHANGES_REQUESTED** [review]
>### Pull Request Under the review by Maria Eugenia Queme P. (TSE)

### Hello @rootDEV2990 and @LoboArkano :balloon: :lollipop: 

### thank you for doing the changes requested by the previous reviewer :medal_sports:  your page is looking better and better every time you should feel very proud of yourselves :star: 

### Some elements of your page were affected with the changes you made so let's fix them, some of the changes are optional too but I think it will make your page look even better :point_down: 

## Medium screens

#### navbar

- [x] The TNW icon at the left corner should take the whole corner, yours has the black bar on top of it, let's fix it.

- yours

image

- Original

image

#### Main articles

- [x] [OPTIONAL] The main articles should be bigger in height (also for Big screens) like the original:

- Yours
image

- Original

image

#### Latest news

- [ ] [OPTIONAL] the articles should be smaller in height and closer together they should look more rectangular like the original

- Yours

image

- Original

image

#### Apps, Gear, Tech sections

- [x] [OPTIONAL] Just like the previous TSE suggested the white letters inside should be smaller

- Yours

image

- Original

image

## Big Screens

#### Navbar

Your navbar still have the behavior pointed out by the previous reviewer please fix it including the yellow stripe is too big it should be smaller like the original

- Yours

image

- Original

image

#### Latest News and Latest Deals

[OPTIONAL] the articles should be closer together and centered in the page

- Yours

image

- Original

image

#### Latest fundings

- [x] [OPTIONAL]The articles should be centered int he page and the navigation links have this order (Add info | Get updates bu email | See more) I strongly recommend doing this optional change because you'll have to do something similar for the Bootstrap project so fixing this would be a good practice

- yours

image

- original

image

#### Apps, Gear, Tech.. etc sections

[OPTIONAL] The articles should be smaller in width and centered in the page

- Yours

image

- Original

image

#### Footer

- [x] The footer icons should be closer together and centered as requested by the previous reviewer

- Yours

image

- Original

image

## All screens

#### Latest news and Latest deals

- [x] [OPTIONAL] the font for Latest news and latest deals title should be bigger like the original

- Yours

image

- Original

image

#### Latest deals

- [ ] [OPTIONAL] The See all Deals red link is missing, consider adding it

image

## Section Specific

#### HTML validator

- [x] You have an error spotted by the HTML [validator](https://validator.w3.org/#validate_by_upload) please fix all HTML errors before requesting for a code review again

image

#### CSS bad practices
 
- [x] I've noticed some selectors that repeat several times making your CSS file bigger than it needs to be please chain define them so you keep the code DRY (don't repeat yourself)

- width: 100%; (4 times)
- color: #f42; (4 times)
- font-size: 12px; (4 times)
- display: grid; (7 times)
- background-position: center; (5 times)
- background-repeat: no-repeat; (6 times)
- display: flex; (8 times)
- text-decoration: none; (8 times)
- display: none; (3 times)
- text-align: left; (3 times)
- flex-direction: row; (4 times)
- height: 48px; (3 times)
- display: grid; (7 times)
- font-weight: 900; (4 times)
- font-size: 14px; (3 times)
- text-transform: uppercase; (4 times)
- color: rgb(255, 255, 255); (4 times)
- color: #555; (3 times)
- color: red; (3 times)
- color: white; (5 times)

### That's it, team! :raised_hands: 

### Please :pray:  do the changes :man_technologist:  :man_technologist: and submit back for a code review when you are done :memo: 

Happy coding! :rocket: 

Any questions? let me know on slack **@ Maru** :woman_technologist: 

PROJECT STATUS: REQUESTED CHANGES :vertical_traffic_light:

**Comment by thsvr** [comment]
### **Status: PROJECT APPROVED** :fireworks: :fireworks::fireworks::fireworks:

Hi @rootDEV2990 and @LoboArkano :smile: :smile: 

Congratulations on the hard work, your project looks beautiful and professional :1st_place_medal: :1st_place_medal: :1st_place_medal: 

Good job on the implementation of all the requests by previously TSE :smile_cat: 






_If you have any questions, don't hesitate to contact me through slack_ [@Thaís Vieira Azevedo](url)


### **Happy coding and good luck on the next project** :desktop_computer: :computer_mouse: 




**_Project reviewd by Thaís Vieira (TSE)_**

**Review by Rathnayaka1988 — CHANGES_REQUESTED** [review]
Fg

**Pull request merged**
